---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/jcapiitao/konflux-rdo-python-ddt?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "c9s-dalmatian-rdo"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: rpms
    appstudio.openshift.io/component: python-ddt
    pipelines.appstudio.openshift.io/type: build
  name: python-ddt-on-pull-request
  namespace: rdo-tenant
spec:
  params:
    - name: package-name
      value: python-ddt
  pipelineRef:
    name: build-rdo-package
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
